// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: cbcbd9666d8107cbc84b8af329e85d3dfc205811595099ee9d818cb44871d0fd
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/qiongtongbaojian/chapters/v1/*.md", { eager: true, query: "?raw", import: "default" }));
