// Generated by scripts/generate-book-adapters.mjs. Do not edit.
import catalogData from "./catalog.json";
import { createBookDefinition } from "@/books/shared/create-book-definition";
import type { BookCatalog } from "@/books/shared/navigation";

const volumeImports = {
  v1: () => import("./volumes/v1"),
  v2: () => import("./volumes/v2"),
  v3: () => import("./volumes/v3"),
  v4: () => import("./volumes/v4"),
  v5: () => import("./volumes/v5"),
  v6: () => import("./volumes/v6"),
  v7: () => import("./volumes/v7"),
  v8: () => import("./volumes/v8"),
  v9: () => import("./volumes/v9"),
  v10: () => import("./volumes/v10"),
  v11: () => import("./volumes/v11"),
  v12: () => import("./volumes/v12"),
};

export default createBookDefinition(
  catalogData as BookCatalog,
  volumeImports,
);
