// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: f281bfe70c272e0a178ea1f3654d107db2ddd8c4dd9d33b96b5649b8ee183388
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/yuanhaiziping/chapters/v1/*.md", { eager: true, query: "?raw", import: "default" }));
