// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: cd54482ba0367cb3a68e36f5960c73f556301e8eaf77223a8bae5df4f9cea83e
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/yuanhaiziping/chapters/v2/*.md", { eager: true, query: "?raw", import: "default" }));
