// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 0b48317552c48ffd868cbbc8027ece9cb2503967c294de4baf4f15daa0ef1aa7
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/yuanhaiziping/chapters/v3/*.md", { eager: true, query: "?raw", import: "default" }));
