// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 87b978be7e7e4cda7fb3ea592ef6bbc697620d175512b3eea14bde235e0e886f
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/yuanhaiziping/chapters/v4/*.md", { eager: true, query: "?raw", import: "default" }));
