// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: f264fc520a16518cb4963a1b5166a4b8b9271c949986032c278f7d0fc1a98207
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/yuanhaiziping/chapters/v5/*.md", { eager: true, query: "?raw", import: "default" }));
