// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: f0888d01e8cff7b1696dfe517897834dc72760ad901ea6fa35a804733bdd7014
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v1/*.md", { eager: true, query: "?raw", import: "default" }));
