// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 7869b9c004c7ff8426c6c985ebca99b06c03edd7ba521ee8be2928fde2e49cb0
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v10/*.md", { eager: true, query: "?raw", import: "default" }));
