// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 74a19f94e3b96b1b45b0d1163105a64db49cdc614b5bec92dd4d7ae200ed8e11
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v11/*.md", { eager: true, query: "?raw", import: "default" }));
