// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 07037c0740be6f32893908525af9214c1c341e80126992814c492f2c3f40205a
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v12/*.md", { eager: true, query: "?raw", import: "default" }));
