// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: d466f7d74ed25724182627971ebe03038e6f6222af3545a5953c63c979051148
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v13/*.md", { eager: true, query: "?raw", import: "default" }));
