// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: ea6a14d1ee73d1b9ea61cf79d356eee0271516040d80e5f1ce18d8a5112cbac2
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v14/*.md", { eager: true, query: "?raw", import: "default" }));
