// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: c951d15d85bb4febedbd207527d52fa023624c9aafb2b3b798c2d39cdc88bea7
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v15/*.md", { eager: true, query: "?raw", import: "default" }));
