// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 686fb061abeead9950993dd4cad14edf2932279ff251efe631272e40e36ddd3d
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v16/*.md", { eager: true, query: "?raw", import: "default" }));
