// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: c54b081ff1873683ccb4d22487906484349c24af47220edfc692d4bd7404bd0f
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v17/*.md", { eager: true, query: "?raw", import: "default" }));
