// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: dc95fe018267cb75ede29f52a3bbaf59ca377b312b6fc42714f50f4e5474d55e
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v18/*.md", { eager: true, query: "?raw", import: "default" }));
