// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 3a835c20f0f14b67f6b8037f94039ef681ed834a14a12b27b2156e19f6b63fda
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v19/*.md", { eager: true, query: "?raw", import: "default" }));
