// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 3773d2c2a87a063f39cd38291bbb7c3d44701778b959d7f09b3063a6d1290b3b
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v2/*.md", { eager: true, query: "?raw", import: "default" }));
