// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 8070001507e750cb8e17fce30290e6a83d1ea2c2c5efba742735646be35d8274
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v20/*.md", { eager: true, query: "?raw", import: "default" }));
