// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 9f0f1934d3d1b284241f88ddf80e25383fe9f8276a543b3c90c87162626b1768
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v3/*.md", { eager: true, query: "?raw", import: "default" }));
