// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 576fe701c99704e8da3ad6752bdc6273c8d85df75860e225080fdca84173b880
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v4/*.md", { eager: true, query: "?raw", import: "default" }));
