// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: de3b3e5e71f4aecc55d14be2d00c2c70d4525966d7c760e7b5317bcd6c6ca037
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v5/*.md", { eager: true, query: "?raw", import: "default" }));
