// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 17737cccfc12f311b81ca86cf2146ede689bbc10a7fab902cc28ec30438ef00d
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v6/*.md", { eager: true, query: "?raw", import: "default" }));
