// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 7ccc9337d307ff10bebc6028736de038d77a8a2b0b07c9a926ce37ff07c3bcaa
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v7/*.md", { eager: true, query: "?raw", import: "default" }));
