// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: f1b1a5ed3bad7230dfb8042e8deee02b785af1839811ddcb38861974aa57e8fb
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v8/*.md", { eager: true, query: "?raw", import: "default" }));
