// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 2d28a2a6b2669a24cc568c28e5e842901e4e251890b7966f857ec2290b116ec6
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/wudenghuiyuan/chapters/v9/*.md", { eager: true, query: "?raw", import: "default" }));
