// Generated by scripts/generate-book-adapters.mjs. Do not edit.
import yuanhaizipingCatalog from "./yuanhaiziping/catalog.json";
import sanmingtonghuiCatalog from "./sanmingtonghui/catalog.json";
import wudenghuiyuanCatalog from "./wudenghuiyuan/catalog.json";
import { BookRegistry, summaryFromCatalog } from "./shared/book-definition";
import type { BookCatalog } from "./shared/navigation";

export const bookRegistry = new BookRegistry([
  {
    catalog: yuanhaizipingCatalog as BookCatalog,
    loadDefinition: () => import("./yuanhaiziping/definition").then((module) => module.default),
  },
  {
    catalog: sanmingtonghuiCatalog as BookCatalog,
    loadDefinition: () => import("./sanmingtonghui/definition").then((module) => module.default),
  },
  {
    catalog: wudenghuiyuanCatalog as BookCatalog,
    loadDefinition: () => import("./wudenghuiyuan/definition").then((module) => module.default),
  }
].map(({ catalog, loadDefinition }) => summaryFromCatalog(catalog, loadDefinition)));
