// Generated by scripts/generate-book-adapters.mjs. Do not edit.
import yuanhaizipingCatalog from "./yuanhaiziping/catalog.json";
import sanmingtonghuiCatalog from "./sanmingtonghui/catalog.json";
import wudenghuiyuanCatalog from "./wudenghuiyuan/catalog.json";
import xinjingCatalog from "./xinjing/catalog.json";
import qiongtongbaojianCatalog from "./qiongtongbaojian/catalog.json";
import { BookRegistry, summaryFromCatalog } from "./shared/book-registry";
import type { BookCatalog } from "./shared/book-runtime";

export const bookRegistry = new BookRegistry([
  {
    catalog: yuanhaizipingCatalog as BookCatalog,
    loadRuntime: () => import("./yuanhaiziping/definition").then((module) => module.default),
  },
  {
    catalog: sanmingtonghuiCatalog as BookCatalog,
    loadRuntime: () => import("./sanmingtonghui/definition").then((module) => module.default),
  },
  {
    catalog: wudenghuiyuanCatalog as BookCatalog,
    loadRuntime: () => import("./wudenghuiyuan/definition").then((module) => module.default),
  },
  {
    catalog: xinjingCatalog as BookCatalog,
    loadRuntime: () => import("./xinjing/definition").then((module) => module.default),
  },
  {
    catalog: qiongtongbaojianCatalog as BookCatalog,
    loadRuntime: () => import("./qiongtongbaojian/definition").then((module) => module.default),
  }
].map(({ catalog, loadRuntime }) => summaryFromCatalog(catalog, loadRuntime)));
