// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 9ee11882c5a7340b85738f8acf1435c6298f3542c97a838b148599d8b1749b67
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/xinjing/chapters/v1/*.md", { eager: true, query: "?raw", import: "default" }));
