// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: b7033cc37c9573a0b34e212c6abaa7337745036653b2580da48ad7f5896bcf2e
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/jingangjing/chapters/v1/*.md", { eager: true, query: "?raw", import: "default" }));
