// Generated by scripts/generate-book-adapters.mjs. Do not edit.
import catalogData from "./catalog.json";
import { createBookRuntime, type BookCatalog } from "@/books/shared/book-runtime";

const volumeImports = {
  v1: () => import("./volumes/v1"),
};

export default createBookRuntime(
  catalogData as BookCatalog,
  volumeImports,
);
