// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 327aea456e188b36f818ff8a3ea9452b5c5dec7a6006be1b147308bed5fecb0e
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v1/*.md", { eager: true, query: "?raw", import: "default" }));
