// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 5b8aa58b816a1b819f0fb698973a42c12caf3e726cc5b62e9cfef758537623d1
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v1/*.md", { eager: true, query: "?raw", import: "default" }));
