// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: d4fc42fdad2f3c48cf80bc6d191b95717b9b89ca9b3d9f627a3a413c0bc55047
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v10/*.md", { eager: true, query: "?raw", import: "default" }));
