// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: b7faa8aa6b31fd5b17641604d37b4057e874e27d466f1be3300f7c813f011c68
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v11/*.md", { eager: true, query: "?raw", import: "default" }));
