// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 960488a1da1d5aa89608cafd1fd9738540dc12719b302427dc7f4fb3300701c5
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v12/*.md", { eager: true, query: "?raw", import: "default" }));
