// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: e65ba37e2be0d7bd2b4178c1a91464cf7ad284ecfeec6229a4794e4511f0a255
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v12/*.md", { eager: true, query: "?raw", import: "default" }));
