// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 68fb88f1960367fe4f444257bef69d7ff5e92b33ed5836023071b23d67ae0207
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v2/*.md", { eager: true, query: "?raw", import: "default" }));
