// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 9c394d86b97aaead1f48421c01f80b0a616bf7b15c96a0ea36bd3a405909ee15
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v3/*.md", { eager: true, query: "?raw", import: "default" }));
