// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 289dd1458b00ae15966d8a5e72af7ab91c91c9a4c7e950783d1cd3a075044810
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v4/*.md", { eager: true, query: "?raw", import: "default" }));
