// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: d321d456d7f9f6559a7a4272b36a54a7de0638e35c2fb045df614d37d4386a11
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v5/*.md", { eager: true, query: "?raw", import: "default" }));
