// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: 1c79221ed6f4e17102bd7dbb2ce9dbe0ce0807658a47e59907dd7f462b0c4255
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v6/*.md", { eager: true, query: "?raw", import: "default" }));
