// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: e1b31aa88088d3a2430813a1068fb0d724997128fab3978183f37216baed1ea1
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v7/*.md", { eager: true, query: "?raw", import: "default" }));
