// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: a1abf27f5a7f466ee585b7c95e672c5f579af8e29e3acf40e2b9eb4a6c72e22c
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v8/*.md", { eager: true, query: "?raw", import: "default" }));
