// Generated by scripts/generate-book-adapters.mjs. Do not edit.
// Catalog chapters: cdfc06a70b124b4be4aada8f41f357b143ef6bf7883245f52b8d997e23165a51
import { chapterContentFromModules } from "@/books/shared/from-modules";
export default chapterContentFromModules(import.meta.glob("../../../../content/books/sanmingtonghui/chapters/v9/*.md", { eager: true, query: "?raw", import: "default" }));
